### PR TITLE
it's markov time.

### PR DESCRIPTION
**Pull request by lourinaldi**
https://github.com/smashwilson/hubot-markov

Run `npm update` and restart Hubot.

### CODE REVIEW

**Comment by treznick** [comment]
I can't get this working on my local (something, something redis ENV variables). Looking through the script though it should work. I'll merge this but leave the PR open in case we need to chat re this

**Comment by treznick** [comment]
didn't blow up

**Comment by ZachBeta** [comment]
Is this even working?

**Comment by ZachBeta** [comment]
Also should we have redis caching every conversation on slack? I trust slack a lot more to secure our messages than us on a fun side bot.

**Comment by treznick** [comment]
all good points. maybe we kill this.

On Fri, Apr 17, 2015 at 3:13 PM, Zach Morek notifications@github.com
wrote:

> Also should we have redis caching every conversation on slack? I trust
> slack a lot more to secure our messages than us on a fun side bot.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/Hubot/pull/5#issuecomment-94055570.

## 

Tom Reznick
Junior Software Engineer, Continuity
914-519-8966

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by jhirbour** [comment]
yea I'm up for killing it.

**Comment by treznick** [comment]
Already dead

On Monday, April 20, 2015, John Hirbour notifications@github.com wrote:

> yea I'm up for killing it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/Hubot/pull/5#issuecomment-94453379.

## 

Sent from my phone. Please excuse brevity and errors.

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Pull request merged**
