### PR TITLE
Hobbes gets oblique strategies

### PR DESCRIPTION
**Pull request by danbernier**
"Hobbes, I'm stuck."
"Dan: Balance the consistency principle with the inconsistency principle."

"Hobbes, I'm stuck."
"Dan: Take away the elements in order of apparent non-importance."

"Thanks Hobbes!"

I have no idea if this is coded correctly. :coffee: script, lol.

### CODE REVIEW

**Comment by treznick** [comment]
I :heart: this! ~~Apparently you need to add script filenames to `hubot-scripts.json`~~(or not, because as both #2 and the docs show, hubot autoloads them) ~~for them to load~~. Also `//` isn't a comment in :coffee: script because it's supposed to be more like :gem: ?? Who knew!?

**Comment by treznick** [comment]
also why on earth does :octocat: not have a ruby emoji?

**Comment by treznick** [comment]
I'll merge and fix this.

**Comment by treznick** [comment]
merged

**Comment by danbernier** [comment]
Thx! Twice!

**Pull request closed without merging**
